name: Jekyll Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # 指定 Ruby 版本，根据你的项目需要选择合适版本
          bundler-cache: true # 启用 Bundler 缓存

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install rexml # 安装 rexml 解决 kramdown 的依赖问题
          bundle install

      # Build the Jekyll site
      - name: Build the Jekyll site
        run: bundle exec jekyll build --baseurl ""

      # Upload the built site as an artifact (可选，用于调试)
      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path: _site
